name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare package
        uses: ./.github/actions/prepare-package
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Verify
        run: |
          bun run format:check
          bun run lint
          bun run type-check
          bun run build
          bun run test

      - run: npm publish --provenance --access public
